;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        org-beginning-of-line
        org-delete-backward-char
        org-delete-char
        org-return-indent
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        org-return
        ))
